### PR TITLE
Building branch

### PR DESCRIPTION
**Pull request by bx44**
A fully-developed version of this project.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Nice job! WOW Project looks! :+1: The readme file is very descriptive!

### But your project needs changes before it can be approved.

Kindly recommended checking HTML markup with this validator https://validator.w3.org/#validate_by_upload.

screenshot

Now it shows errors in your project

errors


#### Also please on small version Navigation and sub-navigation row should change to a hamburger (bars) icon at the rightmost part (next to seach icon) [link to page](https://thenextweb.com/)

* In rightmost part should appear a hamburger icon, as in the original version
original

* In Your version, in a small screen, this element didn`t appear

your

### Top 3 articles section
#### Large version should contains one bigger image on the leftmost part of the row (around two thirds of the width) [link to page](https://thenextweb.com/)

#### Also  Large version should contain two smaller images on the rightmost part of the row (one above another) [link to page](https://thenextweb.com/)

* On the original version as you can see here one big image around 2/3 of the screen and two small images one above another

row

* In your version as I can see three images one above another

row1

####Next, on Small version all images take the maximum width and are aligned in one column [link to page](https://thenextweb.com/)

* Original version

col1

* In your version as we can see here space at the rightmost side

col

### "Latest News" section needs changes in small version

* As you can see it should align 1 article per row

latest

* In your version it aligns 3 articles per row

latest1

### "Latest Funding" section needs changes in the small version

* As you can see it should align 1 article per row
funding

* In your version it aligns 3 articles per row

fun1



### "Categories (Apps, GERA, Tech, etc)" section needs changes in the small version

* It should align 1 article per row

apps

* In your version it aligns 2 articles per row

apps2

### "Latest deals" section needs changes in the small version

* It should align 1 article per row
latest


* In your version it aligns 3 articles per row

latest1


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Comment by Kasuhira** [comment]
@Anna-Myzukina Thank you for your review Anna !
We sure are going to work hard to correct what was pointed, i just wanted to point that some issues, like the "Categories (Apps, GERA, Tech, etc)" section needs changes in the small version",  looks equivocated, since it has the media query for making it 2 columns and one column, in the mobile, for example, it stands in 1 column like you said, the same goes to "the "Latest deals" section needs changes in the small version" issue.

Again, thank you for your feedback, we will post changes soon.

**Comment by Kasuhira** [comment]
@Anna-Myzukina Hello Anna how are you ?

Thanks for the feedback, we appreciate a lot and will work hard to correct the issues.
Just want to point that, we made the website with 3 stages of responsiveness :
- One for desktop
- One for Mobile
- One for tablet

If you reduce more the screen, lets say to 720px<, the two columns will turn into one, and that is the same for the 3 column issue.It is worth a double check.

We apreciate  your time a lot, and will work very hard to correct everything. Tnx !

**Comment by Anna-Myzukina** [comment]
> @Anna-Myzukina Hello Anna how are you ?
> 
> Thanks for the feedback, we appreciate a lot and will work hard to correct the issues.
> Just want to point that, we made the website with 3 stages of responsiveness :
> 
> * One for desktop
> * One for Mobile
> * One for tablet
> 
> If you reduce more the screen, lets say to 720px<, the two columns will turn into one, and that is the same for the 3 column issue.It is worth a double check.
> 
> We apreciate your time a lot, and will work very hard to correct everything. Tnx !

If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.

**Pull request merged**
